version: '3.8'

services:
  # Наш агент мониторинга
  monitor:
    build: . # Собирать из Dockerfile в текущей папке
    image: my-healthcheck:v1 # Тег образа
    environment:
      # Конфигурируем через переменные окружения, как настоящий 12-factor app
      - TARGET_URL=https://fake-site
      - CHECK_TIMEOUT=3
      - CHECK_INTERVAL=15
    # Если сайт упадет, контейнер не должен умереть без причины.
    # Но наш скрипт бесконечный и печатает логи, так что restart здесь не критичен,
    # но хорошая практика для сервисов, которые должны работать всегда.
    restart: unless-stopped 

  # Второй сервис для теста — локальный веб-сервер
  fake-site:
    image: nginx:alpine # Просто Nginx ради эксперимента
    ports:
      - "8088:80" # Пробросим порт, чтобы можно было проверить браузером
